/**
 * PDF Trip Portfolio Generator.
 *
 * Generates a polished, branded PDF document from trip itinerary data
 * using jsPDF. Designed to run client-side so users can download their
 * plan portfolio instantly without a server round-trip.
 *
 * Features:
 *   - Cover page with trip title, dates, and destination
 *   - Day-by-day itinerary breakdown
 *   - Budget summary table
 *   - Notes section
 */

import { jsPDF } from "jspdf";

// ── Brand Palette ─────────────────────────────────────────────────────────────

const COLORS = {
  primary: [41, 98, 255] as [number, number, number],     // Vivid blue
  secondary: [99, 102, 241] as [number, number, number],  // Indigo
  accent: [16, 185, 129] as [number, number, number],     // Emerald
  dark: [30, 41, 59] as [number, number, number],         // Slate-800
  muted: [100, 116, 139] as [number, number, number],     // Slate-500
  light: [241, 245, 249] as [number, number, number],     // Slate-100
  white: [255, 255, 255] as [number, number, number],
};

const PAGE_WIDTH = 210;  // A4 mm
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

// ── Types ─────────────────────────────────────────────────────────────────────

export interface PdfItineraryDay {
  day: number;
  date?: string;
  items: Array<{
    time?: string;
    title: string;
    description?: string;
    category?: string;
    cost?: number;
    currency?: string;
  }>;
}

export interface PdfBudgetSummary {
  totalBudget: number;
  currency: string;
  categories: Array<{
    name: string;
    planned: number;
    actual?: number;
  }>;
}

export interface PdfTripData {
  title: string;
  destinations: string[];
  dateRange?: { start: string; end: string };
  travelers?: number;
  days: PdfItineraryDay[];
  budget?: PdfBudgetSummary;
  notes?: string;
  generatedBy?: string;
}

// ── Generator ─────────────────────────────────────────────────────────────────

/**
 * Generates a trip portfolio PDF and returns it as a Blob.
 *
 * @param data - The trip data to render.
 * @returns A Blob containing the PDF.
 */
export function generateTripPdf(data: PdfTripData): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  let y = 0;

  // ── Cover page ────────────────────────────────────────────────────────────

  // Full-page gradient background (simulated with rectangles)
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, PAGE_WIDTH, 297, "F");

  // Decorative accent bar
  doc.setFillColor(...COLORS.accent);
  doc.rect(0, 0, PAGE_WIDTH, 6, "F");

  // Title block
  y = 80;
  doc.setTextColor(...COLORS.white);
  doc.setFontSize(36);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, PAGE_WIDTH / 2, y, { align: "center" });

  // Destinations
  y += 18;
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  doc.text(data.destinations.join("  •  "), PAGE_WIDTH / 2, y, { align: "center" });

  // Date range
  if (data.dateRange) {
    y += 14;
    doc.setFontSize(12);
    doc.text(
      `${data.dateRange.start}  →  ${data.dateRange.end}`,
      PAGE_WIDTH / 2,
      y,
      { align: "center" },
    );
  }

  // Travelers badge
  if (data.travelers) {
    y += 12;
    doc.setFontSize(11);
    doc.text(`${data.travelers} traveler${data.travelers > 1 ? "s" : ""}`, PAGE_WIDTH / 2, y, {
      align: "center",
    });
  }

  // Footer branding
  doc.setFontSize(10);
  doc.setTextColor(200, 210, 255);
  doc.text(
    data.generatedBy || "Generated by Prayana • prayana-app-7bdf.web.app",
    PAGE_WIDTH / 2,
    270,
    { align: "center" },
  );

  // ── Itinerary pages ───────────────────────────────────────────────────────

  for (const day of data.days) {
    doc.addPage();
    y = MARGIN;

    // Day header bar
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 14, 3, 3, "F");
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    const dayLabel = day.date ? `Day ${day.day} — ${day.date}` : `Day ${day.day}`;
    doc.text(dayLabel, MARGIN + 6, y + 9.5);
    y += 22;

    for (const item of day.items) {
      // Check page overflow
      if (y > 260) {
        doc.addPage();
        y = MARGIN;
      }

      // Time badge
      if (item.time) {
        doc.setFillColor(...COLORS.light);
        doc.roundedRect(MARGIN, y - 4, 22, 8, 2, 2, "F");
        doc.setTextColor(...COLORS.primary);
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.text(item.time, MARGIN + 3, y + 1);
      }

      // Item title
      const titleX = item.time ? MARGIN + 26 : MARGIN;
      doc.setTextColor(...COLORS.dark);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text(item.title, titleX, y);

      // Category chip
      if (item.category) {
        const catX = titleX + doc.getTextWidth(item.title) + 4;
        doc.setFillColor(...COLORS.accent);
        const chipWidth = doc.getTextWidth(item.category) + 6;
        doc.roundedRect(catX, y - 4, chipWidth, 7, 2, 2, "F");
        doc.setTextColor(...COLORS.white);
        doc.setFontSize(7);
        doc.setFont("helvetica", "normal");
        doc.text(item.category, catX + 3, y);
      }

      y += 6;

      // Description
      if (item.description) {
        doc.setTextColor(...COLORS.muted);
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        const descLines = doc.splitTextToSize(item.description, CONTENT_WIDTH - 10);
        doc.text(descLines, MARGIN + 4, y);
        y += descLines.length * 4.5;
      }

      // Cost
      if (item.cost !== undefined) {
        doc.setTextColor(...COLORS.accent);
        doc.setFontSize(9);
        doc.setFont("helvetica", "bold");
        doc.text(
          `${item.currency || "₹"}${item.cost.toLocaleString()}`,
          MARGIN + CONTENT_WIDTH,
          y - (item.description ? 4 : 0),
          { align: "right" },
        );
      }

      y += 6;

      // Separator line
      doc.setDrawColor(...COLORS.light);
      doc.setLineWidth(0.3);
      doc.line(MARGIN, y, MARGIN + CONTENT_WIDTH, y);
      y += 5;
    }
  }

  // ── Budget Summary page ───────────────────────────────────────────────────

  if (data.budget) {
    doc.addPage();
    y = MARGIN;

    // Section header
    doc.setFillColor(...COLORS.secondary);
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 14, 3, 3, "F");
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Budget Summary", MARGIN + 6, y + 9.5);
    y += 24;

    // Total budget highlight
    doc.setTextColor(...COLORS.dark);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text("Total Budget:", MARGIN, y);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...COLORS.primary);
    doc.text(
      `${data.budget.currency} ${data.budget.totalBudget.toLocaleString()}`,
      MARGIN + 45,
      y,
    );
    y += 14;

    // Table header
    doc.setFillColor(...COLORS.light);
    doc.rect(MARGIN, y, CONTENT_WIDTH, 8, "F");
    doc.setTextColor(...COLORS.dark);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Category", MARGIN + 4, y + 5.5);
    doc.text("Planned", MARGIN + 90, y + 5.5);
    doc.text("Actual", MARGIN + 130, y + 5.5);
    y += 12;

    // Table rows
    for (const cat of data.budget.categories) {
      doc.setTextColor(...COLORS.dark);
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(cat.name, MARGIN + 4, y);
      doc.text(`${data.budget.currency} ${cat.planned.toLocaleString()}`, MARGIN + 90, y);
      if (cat.actual !== undefined) {
        const overBudget = cat.actual > cat.planned;
        doc.setTextColor(...(overBudget ? [220, 38, 38] as [number, number, number] : COLORS.accent));
        doc.text(`${data.budget.currency} ${cat.actual.toLocaleString()}`, MARGIN + 130, y);
      } else {
        doc.setTextColor(...COLORS.muted);
        doc.text("—", MARGIN + 130, y);
      }
      y += 7;
    }
  }

  // ── Notes page ────────────────────────────────────────────────────────────

  if (data.notes) {
    doc.addPage();
    y = MARGIN;

    doc.setFillColor(...COLORS.dark);
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 14, 3, 3, "F");
    doc.setTextColor(...COLORS.white);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Notes & Reminders", MARGIN + 6, y + 9.5);
    y += 24;

    doc.setTextColor(...COLORS.dark);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const noteLines = doc.splitTextToSize(data.notes, CONTENT_WIDTH - 8);
    doc.text(noteLines, MARGIN + 4, y);
  }

  return doc.output("blob");
}

/**
 * Generates a trip PDF and triggers a browser download.
 *
 * @param data     - The trip data to render.
 * @param filename - Optional filename (default: "prayana-trip.pdf").
 */
export function downloadTripPdf(data: PdfTripData, filename: string = "prayana-trip.pdf"): void {
  const blob = generateTripPdf(data);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
